// game-bin_bss_0000.c
// Generated by decompiling game-bin
// using Reko decompiler version 0.10.0.0.

#include "game-bin.h"

word32 stderr = 294099520; // 08C3CD20
word32 stdout = 294099584; // 08C3CD40
word32 stdin = 294099592; // 08C3CD44
byte g_b8C3CD48 = 0x00; // 08C3CD48
uint32 g_dw8C3CD4C = 0x00; // 08C3CD4C
