// game-bin_bss_0004.c
// Generated by decompiling game-bin
// using Reko decompiler version 0.10.0.0.

#include "game-bin.h"

word32 g_dw8C7FF10 = 0x00; // 08C7FF10
word32 g_dw8C7FF20 = 0x00; // 08C7FF20
