// game-bin.globals.c
// Generated by decompiling game-bin
// using Reko decompiler version 0.10.0.0.

#include "game-bin.h"

byte g_b0000; // 00000000
byte g_a0001[];
Eq_2159 g_t0004;
<anonymous> g_tFFFFFFFE; // FFFFFFFE
<anonymous> g_tFFFFFFFF; // FFFFFFFF
