// game-bin_init.c
// Generated by decompiling game-bin
// using Reko decompiler version 0.10.0.0.

#include "game-bin.h"

// 0804BE54: void _init()
void _init()
{
	if (g_dw8C39FFC != 0x00)
		__gmon_start__();
	fn0804D180();
	fn08976750();
}

