// game-bin_plt.c
// Generated by decompiling game-bin
// using Reko decompiler version 0.10.0.0.

#include "game-bin.h"

// 0804BEA0: void (Stack bool fArg04, Stack bool fArg08)
void (bool fArg04, bool fArg08)
{
}

// 0804BEB0: void pthread_mutexattr_setpshared()
void pthread_mutexattr_setpshared()
{
}

// 0804BEC0: void SteamAPI_Shutdown()
void SteamAPI_Shutdown()
{
}

// 0804BED0: void wcscpy()
void wcscpy()
{
}

// 0804BEE0: void SDL_GameControllerNameForIndex()
void SDL_GameControllerNameForIndex()
{
}

// 0804BEF0: void __libc_start_main()
void __libc_start_main()
{
}

// 0804BF00: void time()
void time()
{
}

// 0804BF10: void glClearDepth()
void glClearDepth()
{
}

// 0804BF20: void SDL_JoystickClose()
void SDL_JoystickClose()
{
}

// 0804BF30: void __udivdi3()
void __udivdi3()
{
}

// 0804BF40: void pthread_mutexattr_setprotocol()
void pthread_mutexattr_setprotocol()
{
}

// 0804BF50: void SDL_GL_DeleteContext()
void SDL_GL_DeleteContext()
{
}

// 0804BF60: void __isnanf()
void __isnanf()
{
}

// 0804BF70: void std::__throw_bad_alloc()
void std::__throw_bad_alloc()
{
}

// 0804BF80: void __isoc99_sscanf()
void __isoc99_sscanf()
{
}

// 0804BF90: void SDL_SetWindowFullscreen()
void SDL_SetWindowFullscreen()
{
}

// 0804BFA0: void wcslen()
void wcslen()
{
}

// 0804BFB0: void pthread_attr_setstacksize()
void pthread_attr_setstacksize()
{
}

// 0804BFC0: void (Stack (ptr32 Eq_16) ptrArg04, Stack (ptr32 Eq_17) ptrArg08, Stack (ptr32 Eq_18) ptrArg0C, Stack (ptr32 Eq_19) ptrArg10, Stack (ptr32 Eq_20) ptrArg14, Stack (ptr32 Eq_21) ptrArg18, Stack int32 dwArg1C)
void (FMOD_RESULT (* ptrArg04)(const char * ptrArg04, int32 dwArg08, uint32 * ptrArg0C, void ** ptrArg10, void ** ptrArg14), setFileSystem (* ptrArg08)(void * ptrArg04, void * ptrArg08), setFileSystem (* ptrArg0C)(void * ptrArg04, void * ptrArg08, uint32 dwArg0C, uint32 * ptrArg10, void * ptrArg14), setFileSystem (* ptrArg10)(void * ptrArg04, uint32 dwArg08, void * ptrArg0C), setFileSystem (* ptrArg14)(FMOD_ASYNCREADINFO * ptrArg04, void * ptrArg08), setFileSystem (* ptrArg18)(void * ptrArg04, uint32 dwArg08, void * ptrArg0C), int32 dwArg1C)
{
}

// 0804BFD0: void glClearColor()
void glClearColor()
{
}

// 0804BFE0: void __ctype_b_loc()
void __ctype_b_loc()
{
}

// 0804BFF0: void wcsstr()
void wcsstr()
{
}

// 0804C000: void abort()
void abort()
{
}

// 0804C010: void mkdir()
void mkdir()
{
}

// 0804C020: void pthread_mutex_lock()
void pthread_mutex_lock()
{
}

// 0804C030: void pthread_condattr_destroy()
void pthread_condattr_destroy()
{
}

// 0804C040: void (Stack (ptr32 int32) ptrArg04, Stack (ptr32 (ptr32 charconst )) ptrArg08, Stack (ptr32 Eq_25) ptrArg0C)
void (int32 * ptrArg04, const char ** ptrArg08, FMOD_EVENT_INFO * ptrArg0C)
{
}

// 0804C050: void (Stack real32 rArg04)
void (real32 rArg04)
{
}

// 0804C060: void __wcscpy_chk()
void __wcscpy_chk()
{
}

// 0804C070: void asctime()
void asctime()
{
}

// 0804C080: void SDL_GameControllerGetAxis()
void SDL_GameControllerGetAxis()
{
}

// 0804C090: void (Stack int32 dwArg04, Stack uint32 dwArg08, Stack (ptr32 void) ptrArg0C, Stack uint32 dwArg10)
void (int32 dwArg04, uint32 dwArg08, void * ptrArg0C, uint32 dwArg10)
{
}

// 0804C0A0: void SDL_HapticOpenFromJoystick()
void SDL_HapticOpenFromJoystick()
{
}

// 0804C0B0: void (Stack (ptr32 charconst ) ptrArg04)
void (const char * ptrArg04)
{
}

// 0804C0C0: void exit()
void exit()
{
}

// 0804C0D0: void (Stack int32 dwArg04, Stack (ptr32 void) ptrArg08, Stack bool fArg0C)
void (int32 dwArg04, void * ptrArg08, bool fArg0C)
{
}

// 0804C0E0: void pthread_attr_setaffinity_np()
void pthread_attr_setaffinity_np()
{
}

// 0804C0F0: void pthread_create()
void pthread_create()
{
}

// 0804C100: void SDL_JoystickNumAxes()
void SDL_JoystickNumAxes()
{
}

// 0804C110: void __vsnprintf_chk()
void __vsnprintf_chk()
{
}

// 0804C120: void memcpy()
void memcpy()
{
}

// 0804C130: void ()
void ()
{
}

// 0804C140: void memmove()
void memmove()
{
}

// 0804C150: void strncpy()
void strncpy()
{
}

// 0804C160: void fesetexceptflag()
void fesetexceptflag()
{
}

// 0804C170: void (Stack (ptr32 Eq_35) ptrArg04)
void (FMOD_ADVANCEDSETTINGS * ptrArg04)
{
}

// 0804C180: void SteamAPI_RestartAppIfNecessary()
void SteamAPI_RestartAppIfNecessary()
{
}

// 0804C190: void realloc()
void realloc()
{
}

// 0804C1A0: void SDL_HapticClose()
void SDL_HapticClose()
{
}

// 0804C1B0: void glDepthFunc()
void glDepthFunc()
{
}

// 0804C1C0: void glDrawElements()
void glDrawElements()
{
}

// 0804C1D0: void __fprintf_chk()
void __fprintf_chk()
{
}

// 0804C1E0: void SDL_JoystickNumBalls()
void SDL_JoystickNumBalls()
{
}

// 0804C1F0: void fgets()
void fgets()
{
}

// 0804C200: void (Stack int32 dwArg04, Stack (ptr32 Eq_37) ptrArg08, Stack (ptr32 Eq_38) ptrArg0C, Stack (ptr32 Eq_39) ptrArg10, Stack (ptr32 Eq_40) ptrArg14)
void (int32 dwArg04, FMOD_VECTOR * ptrArg08, FMOD_VECTOR * ptrArg0C, FMOD_VECTOR * ptrArg10, FMOD_VECTOR * ptrArg14)
{
}

// 0804C210: void towlower()
void towlower()
{
}

// 0804C220: void isspace()
void isspace()
{
}

// 0804C230: void SDL_ClearError()
void SDL_ClearError()
{
}

// 0804C240: void glColorMask()
void glColorMask()
{
}

// 0804C250: void (Stack (ptr32 (ptr32 void)) ptrArg04)
void (void ** ptrArg04)
{
}

// 0804C260: void SDL_GetWindowGrab()
void SDL_GetWindowGrab()
{
}

// 0804C270: void pthread_mutex_init()
void pthread_mutex_init()
{
}

// 0804C280: void __stack_chk_fail()
void __stack_chk_fail()
{
}

// 0804C290: void SDL_HapticRumbleInit()
void SDL_HapticRumbleInit()
{
}

// 0804C2A0: void (Stack (ptr32 charconst ) ptrArg04, Stack (ptr32 (ptr32 Eq_43)) ptrArg08)
void (const char * ptrArg04, FMOD::EventCategory ** ptrArg08)
{
}

// 0804C2B0: void pthread_cond_destroy()
void pthread_cond_destroy()
{
}

// 0804C2C0: void glFrontFace()
void glFrontFace()
{
}

// 0804C2D0: void __longjmp_chk()
void __longjmp_chk()
{
}

// 0804C2E0: void pthread_condattr_init()
void pthread_condattr_init()
{
}

// 0804C2F0: void __ctype_toupper_loc()
void __ctype_toupper_loc()
{
}

// 0804C300: void FMOD_Event_Stop()
void FMOD_Event_Stop()
{
}

// 0804C310: void (Stack real32 rArg04, Stack real32 rArg08, Stack real32 rArg0C, Stack int32 dwArg10)
void (real32 rArg04, real32 rArg08, real32 rArg0C, int32 dwArg10)
{
}

// 0804C320: void pow()
void pow()
{
}

// 0804C330: void SDL_JoystickNameForIndex()
void SDL_JoystickNameForIndex()
{
}

// 0804C340: void SDL_Quit()
void SDL_Quit()
{
}

// 0804C350: void SDL_GL_SwapWindow()
void SDL_GL_SwapWindow()
{
}

// 0804C360: void glXQueryVersion()
void glXQueryVersion()
{
}

// 0804C370: void SDL_FreeSurface()
void SDL_FreeSurface()
{
}

// 0804C380: void SDL_GameControllerClose()
void SDL_GameControllerClose()
{
}

// 0804C390: void (Stack (ptr32 (ptr32 Eq_48)) ptrArg04)
void (FMOD::EventGroup ** ptrArg04)
{
}

// 0804C3A0: void __cxa_guard_acquire()
void __cxa_guard_acquire()
{
}

// 0804C3B0: void __fxstat()
void __fxstat()
{
}

// 0804C3C0: void _IO_getc()
void _IO_getc()
{
}

// 0804C3D0: void ftell()
void ftell()
{
}

// 0804C3E0: void SDL_JoystickNumHats()
void SDL_JoystickNumHats()
{
}

// 0804C3F0: void sscanf()
void sscanf()
{
}

// 0804C400: void SDL_GL_GetCurrentContext()
void SDL_GL_GetCurrentContext()
{
}

// 0804C410: void __strncpy_chk()
void __strncpy_chk()
{
}

// 0804C420: void glGenTextures()
void glGenTextures()
{
}

// 0804C430: void pthread_join()
void pthread_join()
{
}

// 0804C440: void fwrite()
void fwrite()
{
}

// 0804C450: void __gmon_start__()
void __gmon_start__()
{
}

// 0804C460: void SDL_DisableScreenSaver()
void SDL_DisableScreenSaver()
{
}

// 0804C470: void (Stack (ptr32 charconst ) ptrArg04, Stack uint32 dwArg08, Stack (ptr32 Eq_51) ptrArg0C, Stack (ptr32 (ptr32 Eq_52)) ptrArg10)
void (const char * ptrArg04, uint32 dwArg08, FMOD_CREATESOUNDEXINFO * ptrArg0C, FMOD::Sound ** ptrArg10)
{
}

// 0804C480: void SDL_NumHaptics()
void SDL_NumHaptics()
{
}

// 0804C490: void localtime()
void localtime()
{
}

// 0804C4A0: void glViewport()
void glViewport()
{
}

// 0804C4B0: void SDL_CreateWindow()
void SDL_CreateWindow()
{
}

// 0804C4C0: void __ctype_tolower_loc()
void __ctype_tolower_loc()
{
}

// 0804C4D0: void (Stack real32 rArg04)
void (real32 rArg04)
{
}

// 0804C4E0: void SteamAPI_RegisterCallback()
void SteamAPI_RegisterCallback()
{
}

// 0804C4F0: void SteamAPI_Init()
void SteamAPI_Init()
{
}

// 0804C500: void pthread_cond_init()
void pthread_cond_init()
{
}

// 0804C510: void glGetString()
void glGetString()
{
}

// 0804C520: void strtod()
void strtod()
{
}

// 0804C530: void SDL_HapticRumblePlay()
void SDL_HapticRumblePlay()
{
}

// 0804C540: void dlopen()
void dlopen()
{
}

// 0804C550: void (Stack Eq_54 tArg04, Stack (ptr32 Eq_55) ptrArg04, Stack bool fArg08, Stack (ptr32 (ptr32 Eq_57)) ptrArg0C)
void (Eq_54 tArg04, FMOD::Sound * ptrArg04, bool fArg08, FMOD::Channel ** ptrArg0C)
{
}

// 0804C560: void powf()
void powf()
{
}

// 0804C570: void FMOD_EventSystem_Create()
void FMOD_EventSystem_Create()
{
}

// 0804C580: void pthread_mutex_destroy()
void pthread_mutex_destroy()
{
}

// 0804C590: void strstr()
void strstr()
{
}

// 0804C5A0: void chdir()
void chdir()
{
}

// 0804C5B0: void (Stack (ptr32 Eq_58) ptrArg04)
void (FMOD_EVENT_SYSTEMINFO * ptrArg04)
{
}

// 0804C5C0: void glDepthMask()
void glDepthMask()
{
}

// 0804C5D0: void SDL_HapticRumbleStop()
void SDL_HapticRumbleStop()
{
}

// 0804C5E0: void pthread_attr_init()
void pthread_attr_init()
{
}

// 0804C5F0: void (Stack (ptr32 int32) ptrArg04)
void (int32 * ptrArg04)
{
}

// 0804C600: void (Stack real32 rArg04)
void (real32 rArg04)
{
}

// 0804C610: void __memcpy_chk()
void __memcpy_chk()
{
}

// 0804C620: void FMOD_Memory_Initialize()
void FMOD_Memory_Initialize()
{
}

// 0804C630: void (Stack (ptr32 charconst ) ptrArg04, Stack (ptr32 (ptr32 Eq_62)) ptrArg08)
void (const char * ptrArg04, FMOD::EventParameter ** ptrArg08)
{
}

// 0804C640: void iswspace()
void iswspace()
{
}

// 0804C650: void pthread_cond_wait()
void pthread_cond_wait()
{
}

// 0804C660: void pthread_yield()
void pthread_yield()
{
}

// 0804C670: void SDL_GL_SetSwapInterval()
void SDL_GL_SetSwapInterval()
{
}

// 0804C680: void SDL_NumJoysticks()
void SDL_NumJoysticks()
{
}

// 0804C690: void SDL_GetPrefPath()
void SDL_GetPrefPath()
{
}

// 0804C6A0: void SDL_GetDesktopDisplayMode()
void SDL_GetDesktopDisplayMode()
{
}

// 0804C6B0: void __cxa_guard_release()
void __cxa_guard_release()
{
}

// 0804C6C0: void glTexParameterf()
void glTexParameterf()
{
}

// 0804C6D0: void glEnable()
void glEnable()
{
}

// 0804C6E0: void glClear()
void glClear()
{
}

// 0804C6F0: void SDL_DestroyWindow()
void SDL_DestroyWindow()
{
}

// 0804C700: void __memmove_chk()
void __memmove_chk()
{
}

// 0804C710: void pthread_mutexattr_init()
void pthread_mutexattr_init()
{
}

// 0804C720: void wcsncpy()
void wcsncpy()
{
}

// 0804C730: void (Stack (ptr32 Eq_63) ptrArg04, Stack (ptr32 Eq_64) ptrArg08, Stack (ptr32 Eq_65) ptrArg0C)
void (FMOD_VECTOR * ptrArg04, FMOD_VECTOR * ptrArg08, FMOD_VECTOR * ptrArg0C)
{
}

// 0804C740: void std::__throw_length_error(Stack (ptr32 charconst ) ptrArg04)
void std::__throw_length_error(const char * ptrArg04)
{
}

// 0804C750: void (Stack (ptr32 int32) ptrArg04)
void (int32 * ptrArg04)
{
}

// 0804C760: void _setjmp()
void _setjmp()
{
}

// 0804C770: void stpcpy()
void stpcpy()
{
}

// 0804C780: void fputc()
void fputc()
{
}

// 0804C790: void pthread_mutexattr_settype()
void pthread_mutexattr_settype()
{
}

// 0804C7A0: void strcspn()
void strcspn()
{
}

// 0804C7B0: void ()
void ()
{
}

// 0804C7C0: void FMOD_Event_GetInfo()
void FMOD_Event_GetInfo()
{
}

// 0804C7D0: void (Stack int32 dwArg04, Stack (ptr32 charconst ) ptrArg08, Stack int32 dwArg0C, Stack (ptr32 Eq_71) ptrArg10)
void (int32 dwArg04, const char * ptrArg08, int32 dwArg0C, FMOD_GUID * ptrArg10)
{
}

// 0804C7E0: void clock_gettime()
void clock_gettime()
{
}

// 0804C7F0: void strtoul()
void strtoul()
{
}

// 0804C800: void SDL_SetWindowGrab()
void SDL_SetWindowGrab()
{
}

// 0804C810: void pthread_attr_setschedpolicy()
void pthread_attr_setschedpolicy()
{
}

// 0804C820: void strcmp()
void strcmp()
{
}

// 0804C830: void SteamRemoteStorage()
void SteamRemoteStorage()
{
}

// 0804C840: void SDL_GameControllerGetAttached()
void SDL_GameControllerGetAttached()
{
}

// 0804C850: void rand()
void rand()
{
}

// 0804C860: void memcmp()
void memcmp()
{
}

// 0804C870: void tolower()
void tolower()
{
}

// 0804C880: void FMOD_EventGroup_GetInfo()
void FMOD_EventGroup_GetInfo()
{
}

// 0804C890: void SDL_GameControllerMapping()
void SDL_GameControllerMapping()
{
}

// 0804C8A0: void memset()
void memset()
{
}

// 0804C8B0: void SDL_GetDisplayMode()
void SDL_GetDisplayMode()
{
}

// 0804C8C0: void SDL_JoystickOpen()
void SDL_JoystickOpen()
{
}

// 0804C8D0: void getenv()
void getenv()
{
}

// 0804C8E0: void ()
void ()
{
}

// 0804C8F0: void SDL_CreateRGBSurfaceFrom()
void SDL_CreateRGBSurfaceFrom()
{
}

// 0804C900: void ()
void ()
{
}

// 0804C910: void SDL_GetBasePath()
void SDL_GetBasePath()
{
}

// 0804C920: void pthread_attr_setscope()
void pthread_attr_setscope()
{
}

// 0804C930: void strchr()
void strchr()
{
}

// 0804C940: void FMOD_EventGroup_GetParentGroup()
void FMOD_EventGroup_GetParentGroup()
{
}

// 0804C950: void __vswprintf_chk()
void __vswprintf_chk()
{
}

// 0804C960: void __errno_location()
void __errno_location()
{
}

// 0804C970: void SDL_GL_CreateContext()
void SDL_GL_CreateContext()
{
}

// 0804C980: void SDL_ShowWindow()
void SDL_ShowWindow()
{
}

// 0804C990: void SteamAPI_UnregisterCallback()
void SteamAPI_UnregisterCallback()
{
}

// 0804C9A0: void glStencilFunc()
void glStencilFunc()
{
}

// 0804C9B0: void fread()
void fread()
{
}

// 0804C9C0: void SDL_GameControllerOpen()
void SDL_GameControllerOpen()
{
}

// 0804C9D0: void strcat()
void strcat()
{
}

// 0804C9E0: void glTexParameteri()
void glTexParameteri()
{
}

// 0804C9F0: void __strcat_chk()
void __strcat_chk()
{
}

// 0804CA00: void glStencilOp()
void glStencilOp()
{
}

// 0804CA10: void strtol()
void strtol()
{
}

// 0804CA20: void SDL_GetCurrentDisplayMode()
void SDL_GetCurrentDisplayMode()
{
}

// 0804CA30: void glXGetProcAddressARB()
void glXGetProcAddressARB()
{
}

// 0804CA40: void SteamUserStats()
void SteamUserStats()
{
}

// 0804CA50: void __xstat()
void __xstat()
{
}

// 0804CA60: void feclearexcept()
void feclearexcept()
{
}

// 0804CA70: void pthread_setaffinity_np()
void pthread_setaffinity_np()
{
}

// 0804CA80: void __strcpy_chk()
void __strcpy_chk()
{
}

// 0804CA90: void glClearStencil()
void glClearStencil()
{
}

// 0804CAA0: void SDL_GetDisplayName()
void SDL_GetDisplayName()
{
}

// 0804CAB0: void SDL_GetWindowSize()
void SDL_GetWindowSize()
{
}

// 0804CAC0: void pthread_cond_timedwait()
void pthread_cond_timedwait()
{
}

// 0804CAD0: void __cxa_atexit()
void __cxa_atexit()
{
}

// 0804CAE0: void free()
void free()
{
}

// 0804CAF0: void (Stack (ptr32 (ptr32 Eq_72)) ptrArg04)
void (FMOD::System ** ptrArg04)
{
}

// 0804CB00: void ()
void ()
{
}

// 0804CB10: void SDL_ShowCursor()
void SDL_ShowCursor()
{
}

// 0804CB20: void (Stack uint32 dwArg04, Stack uint32 dwArg08, Stack (ptr32 (ptr32 Eq_75)) ptrArg0C)
void (uint32 dwArg04, uint32 dwArg08, FMOD::Event ** ptrArg0C)
{
}

// 0804CB30: void SDL_SetWindowSize()
void SDL_SetWindowSize()
{
}

// 0804CB40: void (Stack (ptr32 Eq_76) ptrArg04, Stack Eq_77 tArg08)
void (FMOD_RESULT (* ptrArg04)(FMOD_EVENT * ptrArg04, FMOD_EVENT_CALLBACKTYPE tArg08, void * ptrArg08, FMOD_EVENT_CALLBACKTYPE tArg0C, FMOD_EVENT_CALLBACKTYPE tArg0C), Eq_77 tArg08)
{
}

// 0804CB50: void glGetIntegerv()
void glGetIntegerv()
{
}

// 0804CB60: void strrchr()
void strrchr()
{
}

// 0804CB70: void SDL_SetWindowIcon()
void SDL_SetWindowIcon()
{
}

// 0804CB80: void SDL_GameControllerGetButton()
void SDL_GameControllerGetButton()
{
}

// 0804CB90: void pthread_cond_broadcast()
void pthread_cond_broadcast()
{
}

// 0804CBA0: void memchr()
void memchr()
{
}

// 0804CBB0: void ctime()
void ctime()
{
}

// 0804CBC0: void ()
void ()
{
}

// 0804CBD0: void glGetTexLevelParameteriv()
void glGetTexLevelParameteriv()
{
}

// 0804CBE0: void pthread_mutex_unlock()
void pthread_mutex_unlock()
{
}

// 0804CBF0: void fclose()
void fclose()
{
}

// 0804CC00: void SteamUser()
void SteamUser()
{
}

// 0804CC10: void ferror()
void ferror()
{
}

// 0804CC20: void wcscmp()
void wcscmp()
{
}

// 0804CC30: void fileno()
void fileno()
{
}

// 0804CC40: void (Stack int32 dwArg04)
void (int32 dwArg04)
{
}

// 0804CC50: void SDL_SetWindowDisplayMode()
void SDL_SetWindowDisplayMode()
{
}

// 0804CC60: void strcpy()
void strcpy()
{
}

// 0804CC70: void __wcscat_chk()
void __wcscat_chk()
{
}

// 0804CC80: void mbsrtowcs()
void mbsrtowcs()
{
}

// 0804CC90: void glAlphaFunc()
void glAlphaFunc()
{
}

// 0804CCA0: void fputs()
void fputs()
{
}

// 0804CCB0: void pthread_self()
void pthread_self()
{
}

// 0804CCC0: void dlsym()
void dlsym()
{
}

// 0804CCD0: void nanosleep()
void nanosleep()
{
}

// 0804CCE0: void __vfprintf_chk()
void __vfprintf_chk()
{
}

// 0804CCF0: void SDL_GL_GetDrawableSize()
void SDL_GL_GetDrawableSize()
{
}

// 0804CD00: void pthread_exit()
void pthread_exit()
{
}

// 0804CD10: void SDL_JoystickNumButtons()
void SDL_JoystickNumButtons()
{
}

// 0804CD20: void glDisable()
void glDisable()
{
}

// 0804CD30: void __cxa_pure_virtual()
void __cxa_pure_virtual()
{
}

// 0804CD40: void SteamUtils()
void SteamUtils()
{
}

// 0804CD50: void __mbrlen()
void __mbrlen()
{
}

// 0804CD60: void (Stack (ptr32 uint32) ptrArg04)
void (uint32 * ptrArg04)
{
}

// 0804CD70: void fopen()
void fopen()
{
}

// 0804CD80: void pthread_setschedprio()
void pthread_setschedprio()
{
}

// 0804CD90: void malloc()
void malloc()
{
}

// 0804CDA0: void SteamAPI_RegisterCallResult()
void SteamAPI_RegisterCallResult()
{
}

// 0804CDB0: void getcwd()
void getcwd()
{
}

// 0804CDC0: void (Stack (ptr32 void) ptrArg04)
void (void * ptrArg04)
{
}

// 0804CDD0: void pthread_condattr_setpshared()
void pthread_condattr_setpshared()
{
}

// 0804CDE0: void __printf_chk()
void __printf_chk()
{
}

// 0804CDF0: void sysconf()
void sysconf()
{
}

// 0804CE00: void (Stack (ptr32 real32) ptrArg04, Stack Eq_82 tArg08, Stack Eq_82 tArg08, Stack (ptr32 int32) ptrArg08)
void (real32 * ptrArg04, Eq_82 tArg08, Eq_82 tArg08, int32 * ptrArg08)
{
}

// 0804CE10: void SDL_GL_SetAttribute()
void SDL_GL_SetAttribute()
{
}

// 0804CE20: void glDeleteTextures()
void glDeleteTextures()
{
}

// 0804CE30: void SDL_GetError()
void SDL_GetError()
{
}

// 0804CE40: void memalign()
void memalign()
{
}

// 0804CE50: void SDL_GetDisplayBounds()
void SDL_GetDisplayBounds()
{
}

// 0804CE60: void towupper()
void towupper()
{
}

// 0804CE70: void SteamAPI_RunCallbacks()
void SteamAPI_RunCallbacks()
{
}

// 0804CE80: void closedir()
void closedir()
{
}

// 0804CE90: void pthread_attr_setdetachstate()
void pthread_attr_setdetachstate()
{
}

// 0804CEA0: void FMOD_Event_GetParentGroup()
void FMOD_Event_GetParentGroup()
{
}

// 0804CEB0: void glGetError()
void glGetError()
{
}

// 0804CEC0: void pthread_mutexattr_destroy()
void pthread_mutexattr_destroy()
{
}

// 0804CED0: void SteamAPI_UnregisterCallResult()
void SteamAPI_UnregisterCallResult()
{
}

// 0804CEE0: void glTexImage2D()
void glTexImage2D()
{
}

// 0804CEF0: void __vsprintf_chk()
void __vsprintf_chk()
{
}

// 0804CF00: void (Stack bool fArg04)
void (bool fArg04)
{
}

// 0804CF10: void opendir()
void opendir()
{
}

// 0804CF20: void readdir()
void readdir()
{
}

// 0804CF30: void SDL_GetNumVideoDisplays()
void SDL_GetNumVideoDisplays()
{
}

// 0804CF40: void SDL_PollEvent()
void SDL_PollEvent()
{
}

// 0804CF50: void (Stack Eq_86 tArg04)
void (Eq_86 tArg04)
{
}

// 0804CF60: void qsort()
void qsort()
{
}

// 0804CF70: void readlink()
void readlink()
{
}

// 0804CF80: void (Stack (ptr32 charconst ) ptrArg04, Stack (ptr32 Eq_88) ptrArg08, Stack (ptr32 (ptr32 Eq_89)) ptrArg0C)
void (const char * ptrArg04, FMOD_EVENT_LOADINFO * ptrArg08, FMOD::EventProject ** ptrArg0C)
{
}

// 0804CF90: void wcscat()
void wcscat()
{
}

// 0804CFA0: void (Stack (ptr32 (ptr32 Eq_90)) ptrArg04)
void (FMOD::MusicSystem ** ptrArg04)
{
}

// 0804CFB0: void strncmp()
void strncmp()
{
}

// 0804CFC0: void glDrawArrays()
void glDrawArrays()
{
}

// 0804CFD0: void SDL_IsGameController()
void SDL_IsGameController()
{
}

// 0804CFE0: void (Stack (ptr32 int32) ptrArg04)
void (int32 * ptrArg04)
{
}

// 0804CFF0: void fflush()
void fflush()
{
}

// 0804D000: void SDL_GetNumDisplayModes()
void SDL_GetNumDisplayModes()
{
}

// 0804D010: void glBindTexture()
void glBindTexture()
{
}

// 0804D020: void glCullFace()
void glCullFace()
{
}

// 0804D030: void SDL_free()
void SDL_free()
{
}

// 0804D040: void __sprintf_chk()
void __sprintf_chk()
{
}

// 0804D050: void __snprintf_chk()
void __snprintf_chk()
{
}

// 0804D060: void fseek()
void fseek()
{
}

// 0804D070: void SDL_GameControllerAddMapping()
void SDL_GameControllerAddMapping()
{
}

// 0804D080: void SDL_Init()
void SDL_Init()
{
}

// 0804D090: void SteamFriends()
void SteamFriends()
{
}

// 0804D0A0: void pthread_attr_setinheritsched()
void pthread_attr_setinheritsched()
{
}

// 0804D0B0: void pthread_attr_setschedparam()
void pthread_attr_setschedparam()
{
}

// 0804D0C0: void glXGetClientString()
void glXGetClientString()
{
}

// 0804D0D0: void (Stack int32 dwArg04, Stack (ptr32 (ptr32 Eq_93)) ptrArg08)
void (int32 dwArg04, FMOD::EventProject ** ptrArg08)
{
}

// 0804D0E0: void FMOD_Memory_GetStats()
void FMOD_Memory_GetStats()
{
}

