// Guac_bind_0000.c
// Generated by decompiling Guac.exe
// using Reko decompiler version 0.10.0.0.

#include "Guac.h"

// 00C84005: Register (ptr32 Eq_2) fn00C84005(Stack Eq_3 dwArg04, Stack Eq_4 dwArg08, Register out (ptr32 Eq_2) edxOut)
// Called from:
//      Win32CrtStartup
struct Eq_2 * fn00C84005(Eq_3 dwArg04, Eq_4 dwArg08, struct Eq_2 & edxOut)
{
	struct Eq_2 * eax_183;
	if ((word32) *dwArg04 != 23117)
		eax_183 = null;
	else
	{
		word32 ecx_17 = dwArg04 + Mem10[dwArg04 + 0x3C:word32];
		if (ecx_17->dw0000 != 0x4550)
			eax_183 = null;
		else if ((word32) ecx_17->w0004 == 332 && (word32) ecx_17->w0014 == 0xE0)
		{
			if (ecx_17->dw007C == 0x00)
				eax_183 = null;
			else
			{
				struct Eq_44 * ecx_38 = (word32) dwArg04 + ecx_17->dw0078;
				if (ecx_38->dw0018 != 0x00 && ecx_38->dw0014 != 0x00)
				{
					int32 * dwLoc10_220 = (word32) dwArg04 + ecx_38->dw0020;
					word16 * dwLoc1C_221 = (word32) dwArg04 + ecx_38->dw0024;
					uint32 dwLoc0C_222 = ~0x00;
					up32 dwLoc24_223;
					for (dwLoc24_223 = 0x00; dwLoc24_223 < ecx_38->dw0018; ++dwLoc24_223)
					{
						Eq_4 dwLoc28_227 = dwArg08;
						byte * dwLoc2C_230 = (word32) dwArg04 + *dwLoc10_220;
						do
						{
							word32 dwLoc34_235;
							if ((int32) *dwLoc28_227 == 0x00 || (int32) (*dwLoc2C_230) == 0x00)
							{
								if ((int32) *dwLoc28_227 != (int32) (*dwLoc2C_230))
									dwLoc34_235 = 0x01;
								else
									dwLoc34_235 = 0x00;
								goto l00C841B9;
							}
							byte al_100 = *dwLoc28_227;
							byte al_106 = *dwLoc2C_230;
							byte bLoc2D_237 = al_100;
							dwLoc28_227 = (word32) dwLoc28_227 + 1;
							byte bLoc2E_239 = al_106;
							++dwLoc2C_230;
							if ((int32) al_100 == (int32) al_106)
								continue;
							if ((int32) al_100 >= 0x41 && (int32) al_100 <= 0x5A)
								bLoc2D_237 = (byte) ((int32) al_100 | 0x20);
							if ((int32) al_106 >= 0x41 && (int32) al_106 <= 0x5A)
								bLoc2E_239 = (byte) ((int32) al_106 | 0x20);
						} while ((int32) bLoc2D_237 == (int32) bLoc2E_239);
						dwLoc34_235 = 0x01;
l00C841B9:
						if (dwLoc34_235 == 0x00)
						{
							dwLoc0C_222 = (word32) *dwLoc1C_221;
							break;
						}
						++dwLoc10_220;
						++dwLoc1C_221;
					}
					if (dwLoc0C_222 == ~0x00)
						eax_183 = null;
					else if (dwLoc0C_222 > ecx_38->dw0014)
						eax_183 = null;
					else
					{
						edx = dwArg04 + Mem168[dwArg04 + (Mem168[ecx_38 + 0x1C:word32] + dwLoc0C_222 * 0x04):word32];
						eax_183 = edx;
					}
				}
				else
					eax_183 = null;
			}
		}
		else
			eax_183 = null;
	}
	edxOut = edx;
	return eax_183;
}

// 00C84201: void fn00C84201(Stack Eq_179 dwArg04, Stack Eq_180 dwArg08)
// Called from:
//      Win32CrtStartup
void fn00C84201(Eq_179 dwArg04, Eq_180 dwArg08)
{
	Eq_181 dwLoc08_60 = 1000000000;
	int32 dwLoc0C_61;
	for (dwLoc0C_61 = 0x00; dwLoc0C_61 < 0x0A; ++dwLoc0C_61)
	{
		Eq_191 eax_29 = (uint32) ((uint64) dwArg04 /u dwLoc08_60);
		*((word32) dwArg08 + dwLoc0C_61) = (byte) ((int32) (byte) eax_29 + 0x30);
		dwArg04 -= eax_29 *s dwLoc08_60;
		dwLoc08_60.u1 = (uint32) ((uint64) dwLoc08_60 /u 0x0A);
	}
	*((word32) dwArg08 + 0x0A) = 0x00;
}

// 00C84267: Register Eq_4 fn00C84267(Stack Eq_211 dwArg04, Stack int32 dwArg08, Stack Eq_4 dwArg0C)
// Called from:
//      Win32CrtStartup
Eq_4 fn00C84267(Eq_211 dwArg04, int32 dwArg08, Eq_4 dwArg0C)
{
	int32 dwLoc0C_65;
	for (dwLoc0C_65 = 0x00; dwLoc0C_65 < dwArg08; ++dwLoc0C_65)
	{
		dwArg0C = (int32) *((word32) dwArg04 + dwLoc0C_65) << 0x18 ^ dwArg0C;
		int32 dwLoc10_72;
		for (dwLoc10_72 = 0x08; dwLoc10_72 > 0x00; --dwLoc10_72)
		{
			if ((dwArg0C & 0x80000000) != 0x00)
				dwArg0C = dwArg0C << 0x01 ^ 0x488781ED;
			else
				dwArg0C <<= 0x01;
		}
	}
	return dwArg0C;
}

// 00C842EE: Register Eq_241 Win32CrtStartup()
Eq_241 Win32CrtStartup()
{
	word32 * esi_2394 = g_aC85AEC;
	Eq_4 ecx_145;
	word32 * edi_2397 = fp - 0x0398;
	for (ecx_145 = 0xC0; ecx_145 != 0x00; --ecx_145)
	{
		*edi_2397 = *esi_2394;
		++esi_2394;
		++edi_2397;
	}
	word32 dwLoc03FC_2612 = 1710333449;
	Eq_4 dwLoc03F0_2613 = fp - 0x0398;
	int32 dwLoc03F4_2614;
	for (dwLoc03F4_2614 = 0xC0; dwLoc03F4_2614 > 0x00; --dwLoc03F4_2614)
	{
		word32 eax_2377 = *dwLoc03F0_2613;
		*dwLoc03F0_2613 = *dwLoc03F0_2613 ^ dwLoc03FC_2612;
		ecx_145 = dwLoc03F0_2613;
		dwLoc03FC_2612 = eax_2377;
		dwLoc03F0_2613 = (word32) dwLoc03F0_2613 + 4;
	}
	Eq_271 dwLoc0408_2618 = 0x00;
	while (dwLoc0408_2618 < 0x10)
	{
		byte * ecx_2368 = (word32) dwLoc0408_2618 + (fp - 0xD0);
		byte cl_2370 = *ecx_2368;
		Mem2371[fp - 0x90 + dwLoc0408_2618:byte] = cl_2370;
		ecx_145 = SEQ(SLICE(ecx_2368, word24, 8), cl_2370);
		dwLoc0408_2618 = (word32) dwLoc0408_2618 + 1;
	}
	Eq_292 dwLoc0414_2622;
	for (dwLoc0414_2622 = 0x00; dwLoc0414_2622 < 0x28; ++dwLoc0414_2622)
	{
		word32 ecx_2357 = fp - 0xC0 + dwLoc0414_2622;
		Eq_4 cl_2359 = *ecx_2357;
		Mem2360[fp - 0x03D0 + dwLoc0414_2622:byte] = cl_2359;
		ecx_145 = SEQ(SLICE(ecx_2357, word24, 8), cl_2359);
	}
	Eq_312 esp_109 = fp - 0x1018;
	fn00C84267(fp - (union Eq_4 *) 0x0398, 0x0300, fn00C84267(dwLoc0380, dwLoc037C, 0x00)) == dwLoc0378;
	Eq_343 dwLoc041C_2643;
	for (dwLoc041C_2643 = 0x00; dwLoc041C_2643 < 0x60; ++dwLoc041C_2643)
		Mem2349[fp - 0x80 + dwLoc041C_2643:byte] = 0x00;
	if (dwLoc80 == 0x00 && dwLoc0394 != null)
	{
		Eq_3 eax_147;
		(*dwLoc0394)();
		dwLoc80 = eax_147;
	}
	if (dwLoc80 == 0x00 && dwLoc0390 != null)
	{
		*((word32) esp_109 - 4) = fp - 0x0340;
		Eq_3 eax_171;
		(*dwLoc0390)();
		dwLoc80 = eax_171;
	}
	if (dwLoc80 == 0x00 && dwLoc0388 != null)
	{
		*((word32) esp_109 - 4) = fp - 848;
		Eq_3 eax_195;
		(*dwLoc0388)();
		dwLoc80 = eax_195;
	}
	if (dwLoc80 == 0x00 && dwLoc0384 != null)
	{
		*((word32) esp_109 - 4) = fp - 0x0340;
		Eq_3 eax_219;
		(*dwLoc0384)();
		dwLoc80 = eax_219;
	}
	if (dwLoc80 == 0x00)
		int3();
	<anonymous> * dwLoc68_2672;
	if (dwLoc038C != null)
		dwLoc68_2672 = (<anonymous> *) *dwLoc038C;
	else
	{
		Eq_415 esp_234 = esp_109 - 4;
		*esp_234 = fp - 0x0220;
		*((word32) esp_234 - 4) = dwLoc80;
		<anonymous> * eax_239 = fn00C84005(*((word32) esp_234 - 4), *esp_234, out edx);
		ecx_145 = *esp_234;
		dwLoc68_2672 = eax_239;
	}
	byte bLoc0690_2701;
	Eq_445 esp_257 = esp_109 - 4;
	*esp_257 = fp - 0x0250;
	*((word32) esp_257 - 4) = dwLoc80;
	struct Eq_456 * esp_280;
	word32 ecx_281;
	word32 edx_282;
	<anonymous> * eax_283;
	dwLoc68_2672();
	esp_280->tFFFFFFFC = fp - 0x0240;
	esp_280->tFFFFFFF8 = dwLoc80;
	struct Eq_468 * esp_293;
	word32 ecx_294;
	word32 edx_295;
	<anonymous> * eax_296;
	dwLoc68_2672();
	esp_293->tFFFFFFFC = fp - 0x0230;
	esp_293->tFFFFFFF8 = dwLoc80;
	struct Eq_480 * esp_306;
	word32 ecx_307;
	word32 edx_308;
	<anonymous> * eax_309;
	dwLoc68_2672();
	esp_306->tFFFFFFFC = fp - 664;
	esp_306->tFFFFFFF8 = dwLoc80;
	struct Eq_492 * esp_319;
	word32 ecx_320;
	word32 edx_321;
	<anonymous> * eax_322;
	dwLoc68_2672();
	esp_319->tFFFFFFFC = fp - 0x0288;
	esp_319->tFFFFFFF8 = dwLoc80;
	struct Eq_504 * esp_332;
	word32 ecx_333;
	word32 edx_334;
	word32 eax_335;
	dwLoc68_2672();
	esp_332->tFFFFFFFC = fp - 0x02D0;
	esp_332->tFFFFFFF8 = dwLoc80;
	struct Eq_516 * esp_345;
	word32 ecx_346;
	word32 edx_347;
	<anonymous> * eax_348;
	dwLoc68_2672();
	esp_345->tFFFFFFFC = fp - 688;
	esp_345->tFFFFFFF8 = dwLoc80;
	struct Eq_528 * esp_358;
	word32 ecx_359;
	word32 edx_360;
	word32 eax_361;
	dwLoc68_2672();
	esp_358->tFFFFFFFC = fp - 0x0278;
	esp_358->tFFFFFFF8 = dwLoc80;
	struct Eq_540 * esp_371;
	word32 ecx_372;
	word32 edx_373;
	word32 eax_374;
	dwLoc68_2672();
	esp_371->tFFFFFFFC = fp - 0x0260;
	esp_371->tFFFFFFF8 = dwLoc80;
	struct Eq_552 * esp_384;
	word32 ecx_385;
	word32 edx_386;
	<anonymous> * eax_387;
	dwLoc68_2672();
	esp_384->tFFFFFFFC = fp - 0x0210;
	esp_384->tFFFFFFF8 = dwLoc80;
	struct Eq_564 * esp_397;
	word32 ecx_398;
	word32 edx_399;
	<anonymous> * eax_400;
	dwLoc68_2672();
	esp_397->tFFFFFFFC = fp - 0x0200;
	esp_397->tFFFFFFF8 = dwLoc80;
	struct Eq_576 * esp_410;
	word32 ecx_411;
	word32 edx_412;
	<anonymous> * eax_413;
	dwLoc68_2672();
	esp_410->tFFFFFFFC = fp - 0x01F0;
	esp_410->tFFFFFFF8 = dwLoc80;
	struct Eq_588 * esp_423;
	word32 ecx_424;
	word32 edx_425;
	<anonymous> * eax_426;
	dwLoc68_2672();
	esp_423->tFFFFFFFC = fp - 0x01E0;
	esp_423->tFFFFFFF8 = dwLoc80;
	struct Eq_600 * esp_436;
	word32 ecx_437;
	word32 edx_438;
	<anonymous> * eax_439;
	dwLoc68_2672();
	esp_436->tFFFFFFFC = fp - 464;
	esp_436->tFFFFFFF8 = dwLoc80;
	struct Eq_612 * esp_449;
	word32 ecx_450;
	word32 edx_451;
	<anonymous> * eax_452;
	dwLoc68_2672();
	esp_449->tFFFFFFFC = fp - 448;
	esp_449->tFFFFFFF8 = dwLoc80;
	struct Eq_624 * esp_462;
	word32 ecx_463;
	word32 edx_464;
	<anonymous> * eax_465;
	dwLoc68_2672();
	esp_462->tFFFFFFFC = fp - 424;
	esp_462->tFFFFFFF8 = dwLoc80;
	struct Eq_636 * esp_475;
	word32 ecx_476;
	word32 edx_477;
	<anonymous> * eax_478;
	dwLoc68_2672();
	esp_475->tFFFFFFFC = fp - 0x0198;
	esp_475->tFFFFFFF8 = dwLoc80;
	struct Eq_648 * esp_488;
	word32 ecx_489;
	word32 edx_490;
	<anonymous> * eax_491;
	dwLoc68_2672();
	esp_488->tFFFFFFFC = fp - 0x0188;
	esp_488->tFFFFFFF8 = dwLoc80;
	struct Eq_660 * esp_501;
	word32 ecx_502;
	word32 edx_503;
	<anonymous> * eax_504;
	dwLoc68_2672();
	esp_501->tFFFFFFFC = fp - 0x0178;
	esp_501->tFFFFFFF8 = dwLoc80;
	struct Eq_672 * esp_514;
	word32 ecx_515;
	word32 edx_516;
	<anonymous> * eax_517;
	dwLoc68_2672();
	esp_514->tFFFFFFFC = fp - 0x0160;
	esp_514->tFFFFFFF8 = dwLoc80;
	struct Eq_684 * esp_527;
	word32 ecx_528;
	word32 edx_529;
	word32 eax_530;
	dwLoc68_2672();
	esp_527->tFFFFFFFC = fp - 344;
	esp_527->tFFFFFFF8 = dwLoc80;
	struct Eq_696 * esp_540;
	word32 ecx_541;
	word32 edx_542;
	<anonymous> * eax_543;
	dwLoc68_2672();
	esp_540->tFFFFFFFC = fp - 0x0140;
	esp_540->tFFFFFFF8 = dwLoc80;
	struct Eq_708 * esp_553;
	word32 ecx_554;
	word32 edx_555;
	<anonymous> * eax_556;
	dwLoc68_2672();
	esp_553->tFFFFFFFC = fp - 0x0130;
	esp_553->tFFFFFFF8 = dwLoc80;
	<anonymous> * eax_569;
	struct Eq_721 * esp_1692;
	word32 ecx_1693;
	word32 edx_1694;
	dwLoc68_2672();
	if (eax_296 != null && (eax_309 != null && (eax_322 != null && (eax_335 != 0x00 && (eax_348 != null && (eax_361 != 0x00 && (eax_543 != null && (eax_374 != 0x00 && (eax_387 != null && (eax_400 != null && (eax_517 != null && (eax_413 != null && (eax_426 != null && (eax_439 != null && (eax_504 != null && (eax_530 != 0x00 && (eax_452 != null && (eax_465 != null && (eax_478 != null && (eax_491 != null && (eax_556 != null && eax_569 != null)))))))))))))))))))))
		bLoc0690_2701 = 0x01;
	else
		bLoc0690_2701 = 0x00;
	byte bLoc0364_2714;
	if ((word32) bLoc0690_2701 == 0x00)
	{
		bLoc0364_2714 = 0x45;
		goto l00C8574F;
	}
	struct Eq_774 * eax_648;
	eax_569();
	struct Eq_774 * dwLoc0424_2707 = eax_648;
	while (true)
	{
		byte bLoc0425_2709;
		if ((int32) dwLoc0424_2707->t0000 == 0x00)
			break;
		if (dwLoc0424_2707->t0000 == 1836213293)
		{
			bLoc0425_2709 = (byte) dwLoc0424_2707[5];
			goto l00C84834;
		}
		++dwLoc0424_2707;
	}
	bLoc0425_2709 = 0x30;
l00C84834:
	bLoc0364_2714 = bLoc0425_2709;
	if ((int32) bLoc0425_2709 != 0x30)
	{
l00C8574F:
		if ((int32) bLoc0364_2714 != 0x35 && ((int32) bLoc0364_2714 != 0x30 && (int32) bLoc0364_2714 != 0x45))
		{
			if (dwLoc0368 == 0x00)
			{
				word32 eax_1973;
				eax_387();
				dwLoc0368 = eax_1973;
			}
			byte bLoc0669_3652;
			struct Eq_792 * esp_1980 = esp_1692 - 4;
			esp_1980->t0000 = fp - 0x0100;
			esp_1980->dwFFFFFFFC = 0x00;
			esp_1980->dwFFFFFFF8 = 0x00100000;
			struct Eq_808 * esp_1992;
			word32 ecx_1993;
			word32 edx_1994;
			Eq_179 eax_1995;
			eax_452();
			esp_1992->tFFFFFFFC = fp - 288;
			esp_1992->dwFFFFFFF8 = 0x00;
			esp_1992->dwFFFFFFF4 = 0x02;
			word32 eax_2009;
			eax_465();
			if (eax_1995 != 0x00 && eax_2009 != 0x00)
			{
				esp_1692->tFFFFFFFC.u0->a0000 = 5000;
				esp_1692->tFFFFFFF8 = eax_1995;
				word32 eax_2025;
				eax_543();
				if (eax_2025 != 0x00)
					bLoc0669_3652 = 0x47;
				else
				{
					esp_1692->tFFFFFFFC.u0->a0000 = 0x00;
					esp_1692->tFFFFFFF8.u0->a0000 = 0x00;
					esp_1692->tFFFFFFF4.u0->a0000 = 0x00;
					esp_1692->dwFFFFFFF0 = 0x02;
					esp_1692->dwFFFFFFEC = eax_2009;
					struct Eq_997 * eax_2045;
					eax_478();
					if (eax_2045 == null)
						bLoc0669_3652 = 0x48;
					else if (eax_2045->dw0090 != 0x02)
						bLoc0669_3652 = 0x49;
					else if (eax_2045->dw0094 != 0x00)
						bLoc0669_3652 = 0x4A;
					else
					{
						esp_1692->tFFFFFFFC.u0->a0000 = 0x00;
						esp_1692->tFFFFFFF8.u0->a0000 = 0x00;
						esp_1692->tFFFFFFF4.u0->a0000 = 0x00;
						esp_1692->dwFFFFFFF0 = 0x00;
						word32 ecx_2068;
						word32 edx_2069;
						word32 eax_2070;
						eax_556();
						struct Eq_1156 * esp_2074;
						word32 edx_2076;
						word32 eax_2077;
						eax_517();
						eax_2045->dw0098 = eax_2077;
						eax_2045->dw00A0 = dwLoc036C;
						eax_2045->t00A4 = dwLoc0378;
						eax_2045->t00AC = dwLoc0374;
						eax_2045->dw00A8 = (int32) bLoc0364_2714;
						eax_2045->dw009C = eax_2070;
						eax_2045->dw0094 = 0x02;
						esp_2074->dwFFFFFFFC = 5000;
						esp_2074->dwFFFFFFF8 = eax_2070;
						struct Eq_1190 * esp_2104;
						word32 ecx_2105;
						word32 edx_2106;
						word32 eax_2107;
						eax_543();
						esp_2104->ptrFFFFFFFC = eax_2045;
						struct Eq_1197 * esp_2114;
						word32 ecx_2115;
						word32 edx_2116;
						eax_491();
						esp_2114->dwFFFFFFFC = eax_2009;
						struct Eq_1203 * esp_2123;
						word32 ecx_2124;
						word32 edx_2125;
						eax_504();
						esp_2123->tFFFFFFFC = eax_1995;
						struct Eq_1209 * esp_2132;
						word32 ecx_2133;
						word32 edx_2134;
						eax_504();
						esp_2132->dwFFFFFFFC = eax_2070;
						eax_504();
						if (eax_2107 != 0x00)
							bLoc0669_3652 = 0x4C;
						else
							bLoc0669_3652 = 0x30;
					}
				}
			}
			else
				bLoc0669_3652 = 0x35;
			if ((int32) bLoc0669_3652 != 0x30)
			{
				struct Eq_883 * esp_2172 = esp_1692 - 4;
				esp_2172->dw0000 = 0x00;
				esp_2172->dwFFFFFFFC = 0x00;
				esp_2172->tFFFFFFF8 = fp - 800;
				Eq_179 dwLoc03E0_3667 = dwLoc0368 + 0xFF98;
				struct Eq_902 * esp_2191;
				word32 ecx_2192;
				word32 edx_2193;
				word32 eax_2194;
				eax_348();
				esp_2191->tFFFFFFFC = fp - 0x02C0;
				esp_2191->dwFFFFFFF8 = eax_2194;
				<anonymous> * eax_2207;
				dwLoc68_2672();
				Eq_915 dwLoc0674_3754;
				for (dwLoc0674_3754 = 0x00; dwLoc0674_3754 < 0x0300; ++dwLoc0674_3754)
					Mem2341[fp - 0x0398 + dwLoc0674_3754:byte] = 0x00;
				Eq_938 dwLoc067C_3757;
				for (dwLoc067C_3757 = 0x00; dwLoc067C_3757 < 0x60; ++dwLoc067C_3757)
					Mem2333[fp - 0x80 + dwLoc067C_3757:byte] = 0x00;
				if (eax_2207 != null)
				{
					esp_1692->tFFFFFFFC = fp - 0x03B7;
					esp_1692->tFFFFFFF8 = dwLoc03E0_3667;
					fn00C84201(esp_1692->tFFFFFFF8, esp_1692->tFFFFFFFC);
					esp_1692->tFFFFFFFC.u0->a0000 = 0x10;
					esp_1692->tFFFFFFF8 = fp - 0x90;
					esp_1692->tFFFFFFF4 = fp - 0x03D0;
					esp_1692->dwFFFFFFF0 = 0x00;
					eax_2207();
				}
			}
		}
		Eq_780 dwLoc0684_3765;
		for (dwLoc0684_3765 = 0x00; dwLoc0684_3765 < 0x0300; ++dwLoc0684_3765)
			Mem2325[fp - 0x0398 + dwLoc0684_3765:byte] = 0x00;
		Eq_874 dwLoc068C_3768;
		for (dwLoc068C_3768 = 0x00; dwLoc068C_3768 < 0x60; ++dwLoc068C_3768)
			Mem2317[fp - 0x80 + dwLoc068C_3768:byte] = 0x00;
		esp_1692->tFFFFFFFC.u0->a0000 = 0x01;
		Eq_241 eax_2303;
		eax_283();
		return eax_2303;
	}
	struct Eq_862 * eax_689 = fs->ptr0018;
	if (eax_689 == null || (eax_689->ptr0018 != eax_689 || (eax_689->ptr0030 == null || (word32) (eax_689->ptr0030)->b0002 != 0x00)))
		;
	if (false)
	{
		bLoc0364_2714 = 0x54;
		goto l00C8574F;
	}
	if (*dwLoc0374 != dwLoc0378)
	{
		bLoc0364_2714 = 77;
		goto l00C8574F;
	}
	esp_1692->tFFFFFFFC = dwLoc0370;
	esp_1692->tFFFFFFF8.u0->a0000 = 0x00;
	struct Eq_961 * esp_752;
	word32 ecx_753;
	word32 edx_754;
	word32 eax_755;
	eax_413();
	esp_752->dwFFFFFFFC = eax_755;
	struct Eq_968 * esp_760;
	word32 edx_762;
	Eq_179 eax_763;
	eax_426();
	Eq_180 dwLoc043C_2777 = 0x00;
	while (dwLoc043C_2777 < dwLoc0370)
	{
		Mem1942[eax_763 + dwLoc043C_2777:byte] = Mem780[dwLoc0374 + dwLoc043C_2777:byte];
		dwLoc043C_2777 = (word32) dwLoc043C_2777 + 1;
	}
	Eq_4 dwLoc0458_2781 = dwLoc0378;
	word32 * dwLoc0448_2785 = (word32) eax_763 + 4;
	Eq_1033 dwLoc044C_2786;
	for (dwLoc044C_2786 = dwLoc0370 - 0x04 >> 0x02; dwLoc044C_2786 > 0x00; --dwLoc044C_2786)
	{
		Eq_4 eax_1919 = *dwLoc0448_2785;
		*dwLoc0448_2785 = *dwLoc0448_2785 ^ dwLoc0458_2781;
		dwLoc0458_2781 = eax_1919;
		++dwLoc0448_2785;
	}
	struct Eq_1050 * eax_804 = *((word32) eax_763 + dwLoc035C);
	word32 eax_808 = Mem805[eax_763 + dwLoc0358:word32];
	esp_760->tFFFFFFFC = eax_808;
	esp_760->dwFFFFFFF8 = 0x00;
	struct Eq_1065 * esp_821;
	word32 ecx_822;
	word32 edx_823;
	word32 eax_824;
	eax_413();
	esp_821->dwFFFFFFFC = eax_824;
	struct Eq_1072 * eax_832;
	struct Eq_1073 * esp_1035;
	Eq_4 ecx_1012;
	struct Eq_1072 * edx_1044;
	eax_426();
	dwLoc0374 = eax_763;
	Eq_4 eax_837[] = eax_763 + dwLoc0354;
	uint32 dwLoc045C_2802 = 0x55555555;
	uint32 dwLoc0474_2803 = 0x55555555;
	uint32 dwLoc047C_2804;
	for (dwLoc047C_2804 = 0x00; dwLoc047C_2804 < eax_808 >> 0x03; ++dwLoc047C_2804)
	{
		Eq_4 dwLoc0484_3111 = dwLoc047C_2804 << 0x01;
		uint32 eax_1837 = eax_804[dwLoc0484_3111];
		uint32 eax_1843 = eax_804->a0004[dwLoc0484_3111];
		uint32 dwLoc0494_3113 = eax_1837;
		uint32 dwLoc0480_3115 = eax_1843;
		Eq_1245 dwLoc0488_3118 = -0x3910C8E0;
		up32 dwLoc0498_3119;
		for (dwLoc0498_3119 = 0x00; dwLoc0498_3119 < 0x20; ++dwLoc0498_3119)
		{
			word32 ecx_1893 = dwLoc0480_3115 - ((dwLoc0494_3113 << 0x04 ^ dwLoc0494_3113 >>u 0x05) + dwLoc0494_3113 ^ dwLoc0488_3118 + eax_837[(dwLoc0488_3118 >>u 11 & 0x03) * 0x04]);
			dwLoc0488_3118 = (word32) dwLoc0488_3118 + 0x61C88647;
			dwLoc0480_3115 = ecx_1893;
			dwLoc0494_3113 -= (ecx_1893 << 0x04 ^ ecx_1893 >>u 0x05) + ecx_1893 ^ dwLoc0488_3118 + eax_837[(dwLoc0488_3118 & 0x03) * 0x04];
		}
		eax_832[dwLoc0484_3111 * 0x04 / 64] = (struct Eq_1072) (dwLoc0494_3113 ^ dwLoc045C_2802);
		eax_832->a0004[dwLoc0484_3111] = dwLoc0480_3115 ^ dwLoc0474_2803;
		ecx_1012 = dwLoc0484_3111;
		edx_1044 = eax_832;
		dwLoc045C_2802 = eax_1837;
		dwLoc0474_2803 = eax_1843;
	}
	<anonymous> * dwLoc0628_2924;
	if ((word32) eax_832->a0000[0].w0000 != 23117)
	{
		dwLoc0628_2924 = null;
		goto l00C855B7;
	}
	ecx_1012 = eax_832 + Mem857[eax_832 + 0x3C:word32];
	if (*ecx_1012 != 0x4550)
	{
		dwLoc0628_2924 = null;
		goto l00C855B7;
	}
	esp_1035->dwFFFFFFFC = 0x04;
	esp_1035->dwFFFFFFF8 = 0x2000;
	esp_1035->dwFFFFFFF4 = (word32) *((word32) ecx_1012 + 80);
	esp_1035->dwFFFFFFF0 = (word32) *((word32) ecx_1012 + 52);
	Eq_3 eax_890;
	eax_296();
	Eq_3 dwLoc0534_2813 = eax_890;
	if (eax_890 == 0x00)
	{
		esp_1035->dwFFFFFFFC = 0x04;
		esp_1035->dwFFFFFFF8 = 0x2000;
		esp_1035->dwFFFFFFF4 = (word32) *((word32) ecx_1012 + 80);
		esp_1035->dwFFFFFFF0 = 0x00;
		Eq_3 eax_909;
		eax_296();
		dwLoc0534_2813 = eax_909;
	}
	if (dwLoc0534_2813 == 0x00)
	{
		dwLoc0628_2924 = null;
		goto l00C855B7;
	}
	Eq_1394 dwLoc0554_2817;
	for (dwLoc0554_2817 = 0x00; dwLoc0554_2817 < 0x90; ++dwLoc0554_2817)
		Mem1638[fp - 0x0530 + dwLoc0554_2817:byte] = 0x00;
	struct Eq_1423 * esp_930 = esp_1035 - 4;
	esp_930->dw0000 = 0x04;
	esp_930->dwFFFFFFFC = 0x1000;
	esp_930->dwFFFFFFF8 = (word32) *((word32) ecx_1012 + 80);
	esp_930->tFFFFFFF4 = dwLoc0534_2813;
	Eq_1443 eax_950;
	eax_296();
	word32 eax_957 = Mem953[eax_832 + 0x3C:word32] + Mem953[ecx_1012 + 0x54:word32];
	Eq_1444 dwLoc0560_2829 = 0x00;
	while (dwLoc0560_2829 < eax_957)
	{
		Mem1630[eax_950 + dwLoc0560_2829:byte] = Mem968[eax_832 + dwLoc0560_2829:byte];
		dwLoc0560_2829 = (word32) dwLoc0560_2829 + 1;
	}
	word32 ecx_974 = eax_950 + Mem968[eax_832 + 0x3C:word32];
	ecx_974->t0034 = dwLoc0534_2813;
	struct Eq_1472 * dwLoc056C_2838 = &ecx_974->w0014 + 2 + (word32) ecx_974->w0014 / 0x00A8;
	int32 dwLoc0570_2839;
	for (dwLoc0570_2839 = 0x00; dwLoc0570_2839 < (word32) ecx_974->w0006; ++dwLoc0570_2839)
	{
		if (dwLoc056C_2838->dw0010 == 0x00)
		{
			Eq_1554 eax_1567 = *((word32) ecx_1012 + 56);
			if (eax_1567 > 0x00)
			{
				struct Eq_1560 * esp_1571 = esp_1035 - 4;
				esp_1571->dw0000 = 0x04;
				esp_1571->dwFFFFFFFC = 0x1000;
				esp_1571->tFFFFFFF8 = eax_1567;
				word32 ecx_1580 = (word32) dwLoc0534_2813 + dwLoc056C_2838->dw000C;
				esp_1571->dwFFFFFFF4 = ecx_1580;
				ptr32 eax_1587;
				eax_296();
				dwLoc056C_2838->dw0008 = eax_1587;
				Eq_1554 dwLoc057C_2998 = 0x00;
				while (dwLoc057C_2998 < eax_1567)
				{
					*((word32) dwLoc057C_2998 + eax_1587) = 0x00;
					dwLoc057C_2998 = (word32) dwLoc057C_2998 + 1;
				}
			}
		}
		else
		{
			struct Eq_1517 * esp_1506 = esp_1035 - 4;
			esp_1506->dw0000 = 0x04;
			esp_1506->dwFFFFFFFC = 0x1000;
			esp_1506->dwFFFFFFF8 = dwLoc056C_2838->dw0010;
			word32 ecx_1516 = (word32) dwLoc0534_2813 + dwLoc056C_2838->dw000C;
			esp_1506->dwFFFFFFF4 = ecx_1516;
			int32 eax_1528;
			eax_296();
			Eq_1543 eax_1533 = dwLoc056C_2838->dw0010;
			ptr32 ecx_1537 = eax_832 + dwLoc056C_2838->dw0014 / 64;
			Eq_1543 dwLoc0588_2987 = 0x00;
			while (dwLoc0588_2987 < eax_1533)
			{
				*((word32) dwLoc0588_2987 + eax_1528) = *((word32) dwLoc0588_2987 + ecx_1537);
				dwLoc0588_2987 = (word32) dwLoc0588_2987 + 1;
			}
			dwLoc056C_2838->dw0008 = eax_1528;
		}
		++dwLoc056C_2838;
	}
	ecx_1012 = dwLoc0534_2813 - *((word32) ecx_1012 + 52);
	if (ecx_1012 != 0x00 && ecx_974->dw00A4 > 0x00)
	{
		ecx_1012 = (word32) dwLoc0534_2813 + ecx_974->dw00A0;
		Eq_4 dwLoc059C_2848 = ecx_1012;
		while (*dwLoc059C_2848 > 0x00)
		{
			word32 ecx_1449 = dwLoc0534_2813 + Mem1016[dwLoc059C_2848 + 0x00:word32];
			word32 dwLoc05A4_2961 = dwLoc059C_2848 + 0x08;
			uint32 dwLoc05A8_2962;
			for (dwLoc05A8_2962 = 0x00; dwLoc05A8_2962 < *((word32) dwLoc059C_2848 + 4) - 0x08 >> 0x01; ++dwLoc05A8_2962)
			{
				ui32 eax_1476 = (word32) *dwLoc05A4_2961;
				if ((word32) *dwLoc05A4_2961 >> 0x0C == 0x03)
				{
					word32 * eax_1484 = ecx_1449 + (eax_1476 & 0x0FFF);
					*eax_1484 = (word32) ecx_1012 + *eax_1484;
				}
				dwLoc05A4_2961 += 0x02;
			}
			ecx_1012 = dwLoc059C_2848 + Mem1459[dwLoc059C_2848 + 0x04:word32];
			dwLoc059C_2848 = ecx_1012;
		}
	}
	byte bLoc05D5_2860;
	if (ecx_974->dw0084 > 0x00)
	{
		ecx_1012 = (word32) dwLoc0534_2813 + ecx_974->dw0080;
		Eq_4 dwLoc05C0_2856 = ecx_1012;
		while (true)
		{
			struct Eq_1656 * esp_1036 = esp_1035 - 4;
			esp_1036->dw0000 = 0x14;
			esp_1036->tFFFFFFFC = dwLoc05C0_2856;
			word32 eax_1051;
			eax_400();
			if (eax_1051 != 0x00 || *((word32) dwLoc05C0_2856 + 0x0C) == 0x00)
				break;
			word32 ecx_1064 = dwLoc0534_2813 + Mem1041[dwLoc05C0_2856 + 0x0C:word32];
			esp_1035->dwFFFFFFFC = 0x00;
			esp_1035->dwFFFFFFF8 = 0x00;
			esp_1035->dwFFFFFFF4 = ecx_1064;
			Eq_1274 eax_1077;
			eax_348();
			if (eax_1077 == 0x00)
			{
				bLoc05D5_2860 = 0x00;
				goto l00C852D3;
			}
			if (dwLoc0524 >= 0x20)
			{
				bLoc05D5_2860 = 0x00;
				goto l00C852D3;
			}
			Eq_4 dwLoc05C4_2868;
			ui32 * dwLoc05CC_2867;
			*((word32) (fp - 0x0520) + dwLoc0524 * 0x04) = eax_1077;
			++dwLoc0524;
			if (*dwLoc05C0_2856 != 0x00)
			{
				ecx_1012 = dwLoc0534_2813 + Mem1106[dwLoc05C0_2856 + 0x10:word32];
				dwLoc05CC_2867 = dwLoc0534_2813 + Mem1090[dwLoc05C0_2856 + 0x00:word32];
				dwLoc05C4_2868 = ecx_1012;
			}
			else
			{
				ecx_1012 = dwLoc0534_2813 + Mem1097[dwLoc05C0_2856 + 0x10:word32];
				dwLoc05CC_2867 = dwLoc0534_2813 + Mem1090[dwLoc05C0_2856 + 0x10:word32];
				dwLoc05C4_2868 = ecx_1012;
			}
			while (*dwLoc05CC_2867 != 0x00)
			{
				if ((*dwLoc05CC_2867 & 0x80000000) != 0x00)
				{
					ui32 eax_1156 = *dwLoc05CC_2867;
					struct Eq_1900 * esp_1160 = esp_1035 - 4;
					esp_1160->dw0000 = eax_1156 & 0xFFFF;
					esp_1160->tFFFFFFFC = eax_1077;
					word32 eax_1169;
					dwLoc68_2672();
					*dwLoc05C4_2868 = eax_1169;
				}
				else
				{
					word32 ecx_1129 = (word32) dwLoc0534_2813 + *dwLoc05CC_2867;
					struct Eq_1881 * esp_1137 = esp_1035 - 4;
					esp_1137->dw0000 = ecx_1129 + 0x02;
					esp_1137->tFFFFFFFC = eax_1077;
					word32 eax_1150;
					dwLoc68_2672();
					*dwLoc05C4_2868 = eax_1150;
				}
				ecx_1012 = dwLoc05C4_2868;
				if (*dwLoc05C4_2868 == 0x00)
				{
					bLoc05D5_2860 = 0x00;
					goto l00C852D3;
				}
				++dwLoc05CC_2867;
				dwLoc05C4_2868 += 0x04;
			}
			dwLoc05C0_2856 += 0x14;
		}
	}
	bLoc05D5_2860 = 0x01;
l00C852D3:
	if ((word32) bLoc05D5_2860 == 0x00)
	{
		dwLoc0628_2924 = null;
		goto l00C855B7;
	}
	Eq_1697 ecx_1197 = (word32) ecx_974->w0014;
	word32 dwLoc05FC_2894 = ecx_974 + 0x18 + ecx_1197;
	int32 dwLoc0600_2903;
	for (dwLoc0600_2903 = 0x00; dwLoc0600_2903 < (word32) ecx_974->w0006; ++dwLoc0600_2903)
	{
		Eq_1785 eax_1309 = (dwLoc05FC_2894->dw0024 & 0x20000000) == 0x00;
		Eq_1793 eax_1317 = (dwLoc05FC_2894->dw0024 & 0x40000000) == 0x00;
		Eq_1697 eax_1325 = (dwLoc05FC_2894->dw0024 & 0x80000000) == 0x00;
		if ((dwLoc05FC_2894->dw0024 & 0x02000000) != 0x00)
		{
			struct Eq_1836 * esp_1415 = esp_1035 - 4;
			esp_1415->dw0000 = 0x4000;
			esp_1415->dwFFFFFFFC = dwLoc05FC_2894->dw0010;
			esp_1415->dwFFFFFFF8 = dwLoc05FC_2894->dw0008;
			eax_309();
		}
		else
		{
			word32 eax_1339 = (fp - 0x05F8 + (eax_1309 << 0x04) + eax_1317 * 0x08)[eax_1325 * 0x04];
			ecx_1197 = eax_1325;
			Eq_1274 dwLoc060C_2933 = eax_1339;
			if ((dwLoc05FC_2894->dw0024 & 0x04000000) != 0x00)
				dwLoc060C_2933 = eax_1339 | 0x0200;
			up32 eax_1355 = dwLoc05FC_2894->dw0010;
			up32 dwLoc0614_2936 = eax_1355;
			if (eax_1355 == 0x00)
			{
				if ((dwLoc05FC_2894->dw0024 & 0x40) != 0x00)
					dwLoc0614_2936 = ecx_974->dw0020;
				else if ((dwLoc05FC_2894->dw0024 & 0x80) != 0x00)
					dwLoc0614_2936 = ecx_974->dw0024;
			}
			if (dwLoc0614_2936 > 0x00)
			{
				struct Eq_2014 * esp_1384 = esp_1035 - 4;
				esp_1384->t0000 = fp - 0x0618;
				esp_1384->tFFFFFFFC = dwLoc060C_2933;
				esp_1384->dwFFFFFFF8 = dwLoc05FC_2894->dw0010;
				esp_1384->dwFFFFFFF4 = dwLoc05FC_2894->dw0008;
				eax_322();
			}
		}
		++dwLoc05FC_2894;
	}
	if (ecx_974->dw0028 != 0x00)
	{
		ecx_1012 = (word32) dwLoc0534_2813 + ecx_974->dw0028;
		if (ecx_1012 == 0x00)
		{
			dwLoc0628_2924 = null;
			goto l00C855B7;
		}
		struct Eq_1967 * esp_1228 = esp_1035 - 4;
		esp_1228->dw0000 = 0x00;
		esp_1228->dwFFFFFFFC = 0x01;
		esp_1228->tFFFFFFF8 = dwLoc0534_2813;
		word32 eax_1243;
		ecx_1012();
		if (eax_1243 == 0x00)
		{
			dwLoc0628_2924 = null;
			goto l00C855B7;
		}
	}
	struct Eq_1929 * esp_1253 = esp_1035 - 4;
	esp_1253->t0000 = fp - 0xE0;
	esp_1253->tFFFFFFFC = dwLoc0534_2813;
	<anonymous> * eax_1258 = fn00C84005(esp_1253->tFFFFFFFC, esp_1253->t0000, out edx_1044);
	ecx_1012 = esp_1253->t0000;
	esp_1035 = (struct Eq_1073 *) ((char *) &esp_1253->t0000 + 4);
	Eq_1298 eax_1271 = eax_832->t003C;
	Eq_1959 dwLoc0620_2920 = 0x00;
	while (dwLoc0620_2920 < (word32) eax_1271 + 0x00F8)
	{
		Mem1290[eax_950 + dwLoc0620_2920:byte] = 0x00;
		dwLoc0620_2920 = (word32) dwLoc0620_2920 + 1;
	}
	dwLoc0628_2924 = eax_1258;
l00C855B7:
	Eq_4 dwLoc0630_3070[] = null;
	while (dwLoc0630_3070 < dwLoc0358)
	{
		Mem1827[eax_832 + dwLoc0630_3070:byte] = 0x00;
		dwLoc0630_3070 = (Eq_4 (*)[]) ((char *) dwLoc0630_3070 + 1);
	}
	struct Eq_1336 * esp_1674 = esp_1035 - 4;
	esp_1674->ptr0000 = eax_832;
	esp_1674->dwFFFFFFFC = 0x00;
	struct Eq_1346 * esp_1684;
	word32 ecx_1685;
	word32 edx_1686;
	word32 eax_1687;
	eax_413();
	esp_1684->dwFFFFFFFC = eax_1687;
	eax_439();
	if (dwLoc0628_2924 == null)
		bLoc0364_2714 = 66;
	else
	{
		esp_1692->tFFFFFFFC = dwLoc0370;
		esp_1692->tFFFFFFF8 = eax_763;
		struct Eq_1387 * esp_1706;
		word32 ecx_1707;
		word32 edx_1708;
		<anonymous> * eax_1709;
		dwLoc0628_2924();
		Eq_180 dwLoc063C_3084 = 0x00;
		while (true)
		{
			byte bLoc03D8_3104 = (byte) eax_1709;
			if (dwLoc063C_3084 >= dwLoc0370)
				break;
			Mem1818[eax_763 + dwLoc063C_3084:byte] = 0x00;
			++dwLoc063C_3084;
		}
		esp_1706->tFFFFFFFC = eax_763;
		esp_1706->dwFFFFFFF8 = 0x00;
		struct Eq_1409 * esp_1738;
		word32 ecx_1739;
		word32 edx_1740;
		word32 eax_1741;
		eax_413();
		esp_1738->dwFFFFFFFC = eax_1741;
		eax_439();
		if (eax_1709 >= (<anonymous> *) 0xFF)
		{
			Eq_1462 dwLoc0648_3093;
			for (dwLoc0648_3093 = 0x00; dwLoc0648_3093 < 0x0300; ++dwLoc0648_3093)
				Mem1808[fp - 0x0398 + dwLoc0648_3093:byte] = 0x00;
			Eq_1490 dwLoc0650_3096;
			for (dwLoc0650_3096 = 0x00; dwLoc0650_3096 < 0x60; ++dwLoc0650_3096)
				Mem1800[fp - 0x80 + dwLoc0650_3096:byte] = 0x00;
			Eq_241 eax_1794;
			eax_1709();
			return eax_1794;
		}
		bLoc0364_2714 = bLoc03D8_3104;
	}
	goto l00C8574F;
}

word32 g_aC85AEC[] = // 00C85AEC
	{
	};
